name: Email Validator CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clona il codice
        uses: actions/checkout@v3

      - name: Installa Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa pytest
        run: pip install pytest

      - name: Esegui i test
        run: pytest
